### ISSUE TITLE
Prevent double issuing in case of recovery

### ISSUE THREAD

**Issue by tnickelsen** [project-origin/stamp#20]
Right now - when recovering certificates database - we issue certificates twice, since we generate new certificate id's in recovery scenario. This should be prevented.

**Comment by wisbech** [comment]
@tnickelsen this is a critical part of the whole value proposition for the system so it needs to adressed, can you elaborate on the recovery scenario, either with logs or illustrations so we can bring it up in our working groups. The more descriptive the easier it would be to address the double spend issue in recovery. 

I am curious btw - are the recovered certificates generated from the connected time-series ( data ) or are they in an interim queue they are recovered from ?

**Comment by tnickelsen** [comment]
In our setup, we have a MeasurementsSyncer that is responsible for bringing measurements into our system. It polls data from DataHub2, and for each assetid it remembers where it has synced to in time and publishes measurements to our Registry Connector (which is what Stamp will replace). 
So if the database of MeasurementsSyncer goes down and we need recover it, it forgets where in time it has synced and will generate new measurements to publish to Stamp, with new certificate ids.

![image](https://github.com/project-origin/stamp/assets/130448180/88cf879d-e414-43ca-a29a-981e88947c3a)

Let me know if you have further questions.

**Comment by wisbech** [comment]
@tnickelsen Thank you for the explanation. 

Interesting indeed - so it is in case of recovery of the measurement syncer there is an information loss and risk of double issuance.

Would it make sense to make a call to the metering point owner (wallet-owner) for the latest issued certificate and acquire the lost time information that way around ?

**Comment by Soped42** [comment]
I think we need to be slightly careful here.

GSRN's are not guaranteed to be unique over time, at least in the Danish system. Thus we cannot rely on this for unique identification througout an assests life span.

Are there any ways to generate something unique based on multiple variables like geolocation, GSRN etc. to increase confidence in the uniqueness?

Secondly we probably should have a check in the register ensuring a malicous double issuing is harder. Do we have any options on this matter?

**Comment by tnickelsen** [comment]
@wisbech It sounds like a complex solution - we would need to know recipients of all certificates during lost time and have a separate solution that can do exactly that. 

I was thinking along the lines of getting events from DataHub3, which we will in the future (in 1-3 years PROMA). Then we would only have a problem if we get same event twice during a recovery period, depending on how it's going to work.

**Comment by wisbech** [comment]
> @wisbech It sounds like a complex solution - we would need to know recipients of all certificates during lost time and have a separate solution that can do exactly that.
> 
> I was thinking along the lines of getting events from DataHub3, which we will in the future (in 1-3 years PROMA). Then we would only have a problem if we get same event twice during a recovery period, depending on how it's going to work. Of course that is not a solution for now.

Consider it a playhead in a buffer ( coming from a DSP-background ) let us say that the buffer on hourly certification ``365 X 24 = 8760`` possible positions ... save the last position in that buffer on issuance of the certificate and you would be out of the woods. Of course the buffer cannot live in the MeasurementSyncer service, but that would be my two cents on a solution. 

FYI the buffer time starts Jan 01 0000 hrs each year :-)

**Comment by tnickelsen** [comment]
@wisbech I didn't understand that solution :D should we talk about this at the next meeting?

**Comment by tnickelsen** [comment]
This has been solved by #68
